### ISSUE TITLE
private method `load' called for Psych:Module (NoMethodError)

### ISSUE THREAD

**Issue by a2ikm** [a2ikm/ec2list#2]
with v0.0.4,

```
$ ec2list --profile my_profile
/Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:693:in `load_api_config': private method `load' called for Psych:Module (NoMethodError)
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:720:in `define_client_methods'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/ec2/client.rb:87:in `<class:V20130815>'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/ec2/client.rb:86:in `<class:EC2>'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/ec2/client.rb:15:in `<module:AWS>'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/ec2/client.rb:14:in `<top (required)>'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/configuration.rb:455:in `block in add_service'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/configuration.rb:368:in `call'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/configuration.rb:368:in `block in add_option_with_needs'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/service_interface.rb:73:in `initialize'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ec2list-0.0.3/lib/ec2list/command.rb:21:in `new'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ec2list-0.0.3/lib/ec2list/command.rb:21:in `fetch_instances'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ec2list-0.0.3/lib/ec2list/command.rb:12:in `block in run'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core.rb:598:in `memoize'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ec2list-0.0.3/lib/ec2list/command.rb:11:in `run'
    from /Users/foo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ec2list-0.0.3/bin/ec2list:7:in `<top (required)>'
    from /Users/foo/.rbenv/versions/2.2.3/bin/ec2list:23:in `load'
    from /Users/foo/.rbenv/versions/2.2.3/bin/ec2list:23:in `<main>'
```

**Comment by a2ikm** [comment]
This issue was fixed by updating rubygems to v2.5.0 with `gem update --system`.
See https://github.com/rubygems/rubygems/pull/1128, maybe.
